### ISSUE TITLE
using ipfs daemon during action

### ISSUE THREAD

**Issue by ThomasPluck** [ibnesayeed/setup-ipfs#84]
Hello!

I have the following github action test on my `caravela` repository.
```yml
name: Units

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-in-matrix:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    runs-on: ${{ matrix.os }}
    name: Tests in ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    
    - name: Set up IPFS
      uses: ibnesayeed/setup-ipfs@master
      with:
        run_daemon: true
      
    - name: Test
      run: make test
```
This works locally on Ubuntu 20.04 using `act`, but when pushed to github itself, the daemon doesn't appear to be able to make external connections and so the action fails.

Thanks in advance!
